### ISSUE TITLE
Win32 how to download the 3rd code

### ISSUE THREAD

**Issue by coretimes** [cocos2d/cocos2d-x-3rd-party-libs-src#142]
I would like to ask Win32 how to download the 3rd code, I tried a lot of methods are not able to download the code is very anxious, can not give a point to explain it, and now Windows development is not worth you to explain it?

**Comment by coretimes** [comment]
I was the development of the windows git download down after no three room library source code, which is just the.Mak file I want to use what tools to download the source code of the three party library and then vs2015 Compiler? Please say the method is greatly appreciated.

**Comment by coretimes** [comment]
我是windows c++开发使用git下载下来之后没有三房库源码，里面都只是.mak文件我要用什么工具去下载三方库的源码再用vs2015编译？请说下方法不胜感激。

**Comment by coretimes** [comment]
@dumganhar @zilongshanren @ricardoquesada @elnormous

**Comment by minggo** [comment]
the source code is downloaded on fly when building a script. You should checkout the version and download it yourself on windows
