### ISSUE TITLE
能提供一下win32编译环境吗？感激不尽

### ISSUE THREAD

**Issue by coretimes** [cocos2d/cocos2d-x-3rd-party-libs-src#143]
#142 I now want to develop a small game under win32 USES coco2dx to support the xp want oneself to recompile the 3 rd, do you provide inside the bin has compiled win32 compilation library can provide the environment very grateful? Thank you very much!
我现在要在win32下开发个小游戏用到了coco2dx为了支持xp系统要自己重新编译3rd，你们提供的bin里面都有win32编译的库能提供一下编译环境吗感激不尽？我自己去github下载各个版本的库编译各种问题， 能提供下吗？感激不尽！
@zilongshanren @ricardoquesada @elnormous @dumganhar @minggo @xiaofeng11 @stammen @steerlink @martell @stevetranby @super626 @hulefei @fusijie @YamakiHirokazuXX @Watson1978

**Comment by minggo** [comment]
Sorry, we don't have the script to compile on windows, we just compile it with source codes with its own project settings. @stammen provides a PR https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/137 to build on win10, i haven't tried it.
