### ISSUE TITLE
is it on purpose or mistake?

### ISSUE THREAD

**Issue by springrider** [cocos2d/cocos2d-x-3rd-party-libs-src#144]
4961d9e recovered websocket header config with "websockets_header_files=l*.h
", and  months later 66c86a8 reverted it...

**Comment by minggo** [comment]
it is on purpose, because `l*.h` will match unneeded header files

**Comment by springrider** [comment]
the current version of cocos2d-x lite has lws_config.h included.   it is not necessary anymore?

**Comment by minggo** [comment]
it is needed, but can not just use `l*.h` to match it, may be should create a new issue

**Comment by springrider** [comment]
I am not sure why, but after change it back to "l*.h", it only copied the necessary file "lws_config.h" and "libwebsockets.h".. which is the correct behaviour...

**Comment by minggo** [comment]
it is because you only build websocket

**Comment by springrider** [comment]
right, new issue then, thanks.
