### ISSUE TITLE
How to update libpng from 1.6.16 to 1.6.36

### ISSUE THREAD

**Issue by piotrros** [cocos2d/cocos2d-x-3rd-party-libs-src#174]
I've followed setup instructions. I've found rules.mak file in contrib/src/png directory and changed the version here. Yet, running `./build.sh -p=android --libs=png --list`

gives:

```
Supported libraries and versions:
libpng-1.6.16
zlib-1.2.8
LuaJIT-2.1.0-beta2
libwebsockets-master-7355750.tar.xz243aa746ab90e0c22eefec04c152f093d2e5264283c325bc4ed83c5e27683859cebeff2120b0b25f64ed3ad25a75fd089f0ccef6aa6d0862c6b431064
curl-7.52.1
freetype-2.5.5
jpegsrc.v9b
tiff-4.0.3

Chipmunk-7.0.1
openssl-1.1.0c
libbullet-git.tar.xzdc63efa816a846b1e0413a49ffa67f8f88726a81f28b4cfadda50244763b5389ae96d379e4afef2d0ee87a2ffd132a5a344107b6eb0e11081e235d1c9
Box2D-2.3.1.tar.gzc7921f993b9a99b3b9421fefadb039cd475c42d85f5b5a35d7c5401c70491349bb885a02fd31e527de06a8b40d9d49a1fdb92c964e13c04ae092c6b98
```

So it still thinks it's an older version. Anyway, I've tried to compile it:

`./build.sh -p=android --libs=png`

Which resulted:

```
You don't specify a valid build mode, use release mode
checking armv7 is in armv7 x86 arm64 mips
checking x86 is in armv7 x86 arm64 mips
checking arm64 is in armv7 x86 arm64 mips
checking png is in png zlib luajit websockets curl freetype jpeg tiff webp chipmunk openssl bullet box2d uv glsl_optimizer

build armv7 for png in android
generating android standalone toolchain for arm
./build.sh: line 306: /build/tools/make-standalone-toolchain.sh: No such file or directory
```

Indeed, there's no such file. What's more, I don't even have tools directory.

So, what's going on?

I just need newer libpng version.

**Comment by minggo** [comment]
Did you follow the readme

>If you want to build static libraries for Android, you should install NDK. NDK r16 is required at the moment and you should also specify the ANDROID_NDK environment variable in your shell.

**Comment by piotrros** [comment]
I did. Guess I had wrong ndk16 version, but that won't explain missing file :) Anyway I don't need to do it anymore.
