### ISSUE TITLE
suggest add -fPIC to linux.ini

### ISSUE THREAD

**Issue by dannyZhou** [cocos2d/cocos2d-x-3rd-party-libs-src#59]
hi . 
if i want to make cocos2d-x to dynamic library , I need to make all static library to add -fPIC
so i suggest add -fPIC to linux.ini 

such that 
cfg_build_release_mode="-O3 -fPIC -DNDEBUG"
cfg_build_debug_mode="-O0 -fPIC -g -DDEBUG"

**Comment by zilongshanren** [comment]
@dannyZhou  You could change it when compiling your libs.

**Comment by dannyZhou** [comment]
OK, thank you !
