### ISSUE TITLE
Can't compiled luajit android arm64-v8a

### ISSUE THREAD

**Issue by SiriusSalvatore** [cocos2d/cocos2d-x-3rd-party-libs-src#91]
when i complied luajit android arm64,it shows "ignore luajit arm64"

**Comment by zilongshanren** [comment]
@SiriusSalvatore 
luajit doesn't support arm64...

**Comment by SiriusSalvatore** [comment]
is it means android arm64 phone can't use luajit ?

**Comment by zilongshanren** [comment]
@SiriusSalvatore  
Now Luajit 2.1 beta supports 64 bit now, I will consider to add the arm64 support later.

**Comment by zilongshanren** [comment]
fixed at : https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/123
